### ISSUE TITLE
paulxstretch vst/clap plugin fails to load in bitwig/ardour

### ISSUE THREAD

**Issue by chrisanthropic** [osam-cologne/archlinux-proaudio#113]
I'm unable to load the paulxstretch vst or clap plugin in my DAW (Mixbus & Ardour).

Bitwig completely fails to load the vst plugin:
![bitwig-vst](https://user-images.githubusercontent.com/6154548/192072511-42c9bc40-44bd-46c7-acd6-dd89af2fe9a6.png)

Bitwig initially fails to load the clap plugin:
![bitwig-clap](https://user-images.githubusercontent.com/6154548/192072554-5fd68f7d-9520-4e01-a08e-223282fd3627.png)

but if I click the 'reload all plugins' button it loads the generic UI:
![bitwig-clap2](https://user-images.githubusercontent.com/6154548/192072588-8999f71a-eaaf-4fe8-8a7f-80f7b136c631.png)

Attempting to open the UI crashes the plugin again.

Ardour/Mixbus both fail to load the vst plugin at all and give me this error `[WARNING]: VST3</usr/lib/vst3/PaulXStretch.vst3>: Scan Failed.`

**Comment by cbix** [comment]
Thanks for reporting. Are you on X11 or Wayland? What Display Manager are you using?
Could be this issue https://github.com/essej/paulxstretch/issues/23
But to confirm, could you try the following:
> - open Ardour, then Window → Plugin Manager
> - either _Re-scan all_ or find PaulXStretch, select the _Ign_ checkbox and then _Re-scan selected_

**Comment by chrisanthropic** [comment]
I have the same behavior on X11 & Wayland, both using KDE/Plasma.

When rescanning the plugin in Ardour, I get this error
```
VST3 module-path '/usr/lib/vst3/PaulXStretch.vst3/Contents/x86_64-linux/PaulXStretch.so'
[Info]: Scanning: /usr/lib/vst3/PaulXStretch.vst3
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  54
  Current serial number in output stream:  54
Scan Failed.
```

**Comment by cbix** [comment]
As the issue seems to depend on the DM, I fear SDDM and xinit are both causing the same problem. I'll try testing with SDDM next week.

**Comment by chrisanthropic** [comment]
Got it, thanks for looking into it!
