### ISSUE TITLE
rtcqs should optionally depend on python-pysimplegui

### ISSUE THREAD

**Issue by SpaceBison** [osam-cologne/archlinux-proaudio#222]
After installing `rtcqs`, running `rtcqs_gui` results in an error (missing `PySimpleGUI`), while `rtcqs` works fine. Installing `python-pysimplegui` fixes that, so it should be included as an optional dependency.

**Comment by SpotlightKid** [comment]
`rtcqs` [already optionally depends](https://github.com/osam-cologne/archlinux-proaudio/blob/master/packages/rtcqs/PKGBUILD#L13) on `python-pysimplegui`.

`pacman` will not install optional dependencies automatically, you have to explicitly install them, if you want them.
