### ISSUE TITLE
Generate web view of available packages at https://arch.osamc.de/

### ISSUE THREAD

**Issue by diovudau** [osam-cologne/archlinux-proaudio#27]
Generate web view of available packages at https://arch.osamc.de/

**Comment by SpotlightKid** [comment]
For starters, we could just enable [FancyIndexing](https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html#indexoptions.fancyindexing) in an `.htaccess`  file.

**Comment by cbix** [comment]
I already enabled that for https://arch.osamc.de/proaudio and added links to the badges in the README:

[![x86_64](https://arch.osamc.de/proaudio/x86_64/badge-count.svg)](https://arch.osamc.de/proaudio/x86_64/?P=*.pkg.tar.zst)
[![aarch64](https://arch.osamc.de/proaudio/aarch64/badge-count.svg)](https://arch.osamc.de/proaudio/aarch64/?P=*.pkg.tar.xz)

In the long term it could be nice to have a Hugo static site built from this repo (on pushes to master, after both build pipelines) and pushed to https://arch.osamc.de/ rendering the README.md and the list of packages in a nicer format.

**Comment by SpotlightKid** [comment]
> t could be nice to have a Hugo static site

Or [Pelican](https://blog.getpelican.com/) or [Nikola](https://getnikola.com/) :wink:

**Comment by cbix** [comment]
> Or [Pelican](https://blog.getpelican.com/) or [Nikola](https://getnikola.com/) wink

Haven't worked with these yet but yea, we should choose something that most of us feel comfy working with :)

**Comment by cbix** [comment]
Played around with Hugo a bit in [`test/hugo-site`](https://github.com/osam-cologne/archlinux-proaudio/tree/test/hugo-site), it just renders the README + a table of all packages that is parsed from the previously extracted database files. No CSS yet but we could check out [syui/hugo-theme-arch](https://github.com/syui/hugo-theme-arch) or just use something basic. Also has [a small drone pipeline](https://github.com/osam-cologne/archlinux-proaudio/blob/a1fe2d1f00a3e3d5bfcf78f19d7bbeecf4e1cc57/.drone.yml#L325:L342).

![Screenshot from 2022-03-29 19-45-16](https://user-images.githubusercontent.com/1295945/160673074-9f7fd81e-ffe4-48a6-a527-2c0def15db7e.png)

AFAIK Hugo doesn't let you create pages from just data, i.e. if we want individual package details pages we probably need an `_index.md` for each package. Maybe there are some workarounds, though, didn't spend much more time on that.

I'm fine with just a single page listing all the packages, optionally with some basic filters and accordion-style details sections, but we can also look into other static site generators.

**Comment by SpotlightKid** [comment]
If we want to display meta-data read from the packages, we probably either have to write a plugin for the static site generator of choice (that's one reason why I suggested examples implemented in Python). Or we would need another step in the CI, which generates JSON/YAML meta-data files for each package, which the site generator can use. Or a combination of both.
