### ISSUE TITLE
Problematic commands regarding partial upgrades in the readme 

### ISSUE THREAD

**Issue by christian-heusel** [osam-cologne/archlinux-proaudio#357]
Generally speaking [partial upgrades are unsupported](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported) and `pacman -Sy` is a prime example on how to create a partial upgrade situation. The readme mentions this command in two places that shoud most likely be changed: 
https://github.com/osam-cologne/archlinux-proaudio/blob/ba9d8eff73356b953b0d9b331fd7c6444485673f/README.md?plain=1#L31
I'd change that to `pacman -Syu <packagename>`.

https://github.com/osam-cologne/archlinux-proaudio/blob/ba9d8eff73356b953b0d9b331fd7c6444485673f/README.md?plain=1#L38
I'd change that to `pacman -S <packagename>`.

**Comment by SpotlightKid** [comment]
I agree with the suggestion for the first change, but don't understand the reasoning for the second one. Can you elaborate? Why not `pacman -Syu debuginfod`?

**Comment by christian-heusel** [comment]
The first one requires to update the sync databases (initially) so that pacman knows which packages are available in the repo.
For the second one we can just install the package as is, so there is no need to have the `-y(u)` with the command 👍🏻

**Comment by SpotlightKid** [comment]
Hmm, I'm not sure I follow. When installing `debuginfod`, we should also make sure that everything is up to date. Users might not follow the readme sequentially. Anyway, I don't think it hurts to also have `-Syu` in there.
