### ISSUE TITLE
[seq66] unable to build

### ISSUE THREAD

**Issue by visionm45** [osam-cologne/archlinux-proaudio#389]
I have tried to build this a few times and i always run into errors. I am running arch linux and so I use yay.  I would expect all of the dependencies to be included so I am not sure what the error is about but I am getting the following on build

``nsm/nsmbase.cpp: In member function 'void seq66::nsmbase::add_server_method(seq66::nsm::tag, lo_method_handler)':
nsm/nsmbase.cpp:885:37: error: cannot convert 'lo_server_thread' {aka 'lo_server_thread_*'} to 'lo_server' {aka 'lo_server_*'}
  885 |         (void) lo_server_add_method(m_lo_server_thread, m, p, h, this);
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     lo_server_thread {aka lo_server_thread_*}
In file included from /usr/include/lo/lo.h:32,
                 from ../include/nsm/nsmbase.hpp:28,
                 from nsm/nsmbase.cpp:126:
``

**Comment by SpotlightKid** [comment]
Confirmed. Seems to be an upstream issue caused maybe by changes in GCC or `liblo`.

I can't find a ticket for it at https://github.com/ahlstromcj/seq66/issues

Would you care to open one there?

**Comment by visionm45** [comment]
[got it](https://github.com/ahlstromcj/seq66/issues/126)

**Comment by visionm45** [comment]
It sounds like the aur package might be out of date.  I'm not sure how to check that, but also I was told that the problem was fixed "on March 11 and 12 in the "portfix" branch."

**Comment by SpotlightKid** [comment]
Well, upstream needs to release a new version containing the fix then.

The last release is 0.99.12 from early Jan 2024:

https://github.com/ahlstromcj/seq66/releases/tag/0.99.12

**Comment by cbix** [comment]
@visionm45 I just pushed a fix containing the patch you mentioned, thanks for your effort!

**Comment by visionm45** [comment]
Thank you!
