### ISSUE TITLE
Auto push airwindows-lv2 to AUR

### ISSUE THREAD

**Issue by blacktowel** [osam-cologne/archlinux-proaudio#392]
Currently `airwindows-lv2` is out of date in AUR

Would be cool to add it to
https://github.com/osam-cologne/archlinux-proaudio/blob/master/aur/packages

**Comment by SpotlightKid** [comment]
Hmm, that didn't work. The [build logs](https://ci.cbix.de/osam-cologne/archlinux-proaudio/1764/1/15) says, the update was pushed to the AUR, but the new version does not show up and there's no commit in the AUR packages repo.

Need to investigate.

**Comment by SpotlightKid** [comment]
Uh, damn, it's `airwindows-lv2`, not `airwindows.lv2`.
