### ISSUE TITLE
Package jack_transport_link

### ISSUE THREAD

**Issue by tkna91** [osam-cologne/archlinux-proaudio#446]
- Name: `jack_transport_link`
- Suggest a [package name](https://wiki.archlinux.org/title/PKGBUILD#pkgname): `jack_transport_link`
- Short [description](https://wiki.archlinux.org/title/PKGBUILD#pkgdesc): `A bridge between Jack's Transport mechanism and Ableton's Link synchronization`
- Latest release version: `none` yet.
- Website: https://github.com/x37v/jack_transport_link
- Source code: https://github.com/x37v/jack_transport_link.git
- AUR (if exists): `none`
- License(s): `GNU General Public License, version 2`
- Is the project active? `yes`
- I have successfully built this myself on Arch: `no`

This appears to be an attempt to improve on [jack_link](https://github.com/rncbc/jack_link).
Please consider packaging this software.

**Comment by SpotlightKid** [comment]
It seems that building this software from source needs the build tool [conan](https://aur.archlinux.org/packages/conan), whch is only available in the AUR and in turn depends on two more Python packages only available in the AUR (python-patch-ng and python-pluginbas).

We can't package software in our repo, which has dependencies on the AUR, even for `makedepebds`.

Additionally, when trying to build the sofware wih conan installed, I get this error:  

```
$ cmake -B build -S $(pwd) -DINSTALL_SERVICE_FILE=OFF
-- Conan: checking conan executable
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 2.4.1
-- Conan executing: /usr/bin/conan install . --build missing --settings build_type=Release --settings compiler=gcc --settings compiler.version=14 --settings compiler.libcxx=libstdc++11 --settings compiler.cppstd=17
ERROR: The default build profile '/home/chris/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>'
CMake Error at build/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:39 (conan_cmake_install)


-- Configuring incomplete, errors occurred!
```

Until both these issues are resolved, I'm afraid we have to give this one a pass.

**Comment by tkna91** [comment]
@SpotlightKid Okay, I see. Thank you for investigating this in detail.
