### ISSUE TITLE
ratatouille.lv2 0.7-1 build failed

### ISSUE THREAD

**Issue by TeamB12** [osam-cologne/archlinux-proaudio#456]
Build failed:
check failed:
 build finish, . . . 
 =================== DONE =======================
==> Starting check()...
lv2lint 0.16.2
...
lilv_world_load_bundle(): note: New version 7.0 found in <file:///home/lee/.cache/rua/build/ratatouille.lv2/src/Ratatouille.lv2-v0.7/bin/Ratatouille.lv2/>
<urn:brummer:ratatouille>
/home/lee/.cache/rua/build/ratatouille.lv2/PKGBUILD: line 26:  1977 Aborted                 lv2lint -M pack -s '_Z*' -I bin/$_name "$_plugin_uri"
==> ERROR: A failure occurred in check().
    Aborting...
Build failed with exit code 4 in /home/lee/.cache/rua/build/ratatouille.lv2

Would not be a problem to work around that, but reporting here might be a good idea.
Building with and without rua will end with the same error message.
Artix Linux here, up2date [please dont ask again]

**Comment by SpotlightKid** [comment]
Probably lv2lint is segfaulting when loading the plugin. I had that problem on my local system (Manjaro) too.

The build from our CI works, though, and also works without problems when I install it on my system. I don't really see what I could fix here.

It might be good to report this upstream.

**Comment by TeamB12** [comment]
It is fully stable building and running:
I have disabled check section in the makeplg file and the problem is solved here.
The  error is rare but does happen - not only on Arch based systems.
This is an issue that I would align or assign (who knows anyway) to the dev people - that is not a user topic.
Thanks for your answer and good luck.

**Comment by TeamB12** [comment]
Just fyi: ratatouille.lv2 0.9-1 still the same issue.

**Comment by SpotlightKid** [comment]
Like I said, I suggest you open an upstream issue about this.

> This is an issue that I would align or assign (who knows anyway) to the dev people - that is not a user topic.

I don't understand what you mean here. What is this supposed to mean? I'm not a dev of Ratatouille.lv2, we just package it. And for the free and open source software ecosystem to work, users are not fundamentally different from developers. If you want to get something fixed, the first step is to report problems in the right place.

**Comment by TeamB12** [comment]
Thank you for your support, anyways.
The issue is still existing.
I did a bug or issue report upstream:
https://github.com/brummer10/Ratatouille.lv2/issues/29
crossing fingers.
