### ISSUE TITLE
The package vcvrack is missing dependencies

### ISSUE THREAD

**Issue by laci37** [osam-cologne/archlinux-proaudio#510]
On a fresh Manjaro install `yay -S vcvrack` fails without installing these packages first:
* patch
* fakeroot
* pkg-config
* make
* gcc

I don't know much about pacman packages, but I think these should be added to makedepends.

**Comment by SpotlightKid** [comment]
These are all deps of the [base-devel](https://archlinux.org/packages/core/any/base-devel/) meta-package, which is always assumed to be installed when building AUR packages.

https://wiki.archlinux.org/title/Arch_User_Repository#Getting_started
