### ISSUE TITLE
Package paulxstretch

### ISSUE THREAD

**Issue by spectromas** [osam-cologne/archlinux-proaudio#60]
- Name: paulxstretch
- Suggest a [paulxstretch](https://wiki.archlinux.org/title/PKGBUILD#paulxstretch):
- Short [description](https://wiki.archlinux.org/title/PKGBUILD#pkgdesc): This application/plugin is based on the PaulStretch algorithm.
- Latest release version: [v1.5.3](https://github.com/essej/paulxstretch/releases/tag/v1.5.3)
- Website: https://sonosaurus.com/paulxstretch/
- Source code: https://github.com/essej/paulxstretch
- License(s): GNU General Public License v.3 license with App Store license exception
- Is the project active? yes
- I have successfully built this myself on Arch: no

## Packaging hints
Looks like juce is required which is why I haven't been able to build it. 

## Comments

I can't believe there's no paulstretch available in the arch repos, even the aur version of the original doesn't build for me.

**Comment by diovudau** [comment]
> I can't believe there's no paulstretch available in the arch repos, even the aur version of the original doesn't build for me.

That may be because paulstretch was always in Audacity and everybody just used that.
